services:
  library:
    build: .
    image: library-app:latest
    container_name: library
    restart: unless-stopped
    environment:
      - CONFIG=/data/config.toml
    volumes:
      - /mnt/RED_2TB/storage/Downloads/fb2.Flibusta.Net:/library:ro
      - /mnt/RED_2TB/storage/books:/books:ro
      - /mnt/RED_2TB/docker/library/data:/data:rw
      - /mnt/RED_2TB/docker/library/static:/app/static:ro
    networks:
      - caddy_default

networks:
  caddy_default:
    external: true
